version: 2.1

executors:
  python-executor:
    docker:
      - image: python:3.7
    working_directory: ~/project

jobs:
  test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest

  docs-build:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Build documentation
          command: |
            cd docs
            make html
      - persist_to_workspace:
          root: docs/_build
          paths: html

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test
      - docs-build
