version: 2.1

executors:
  python-executor:
    docker:
      - image: python:3.7
    working_directory: ~/project

jobs:
  test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest

  docs-build:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Build documentation
          command: |
            cd docs
            make html
      - persist_to_workspace:
          root: docs/_build
          paths: html

  docs-deploy:
    docker:
      - image: cimg/node:16.17 # Replace with your preferred Node version
    steps:
      - checkout
      - attach_workspace:
          at: docs/_build
      - run:
          name: Disable Jekyll for GitHub Pages
          command: touch docs/_build/html/.nojekyll
      - run:
          name: Install gh-pages tool
          command: npm install -g gh-pages@3.2.3
      - run:
          name: Configure Git for deployment
          command: |
            git config --global user.email "ci-build@example.com"
            git config --global user.name "CI Build"
      - run:
          name: Deploy documentation to GitHub Pages
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist docs/_build/html

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test
      - docs-build
      - docs-deploy:
          requires:
            - test
            - docs-build
          filters:
            branches:
              only: main
